default: &default
  username: <%= ENV.fetch("DB_USER") { "meetings_dev" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "p@ssword123" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meetings_development

test:
  <<: *default
  database: meetings_test

production:
  <<: *default
  database: meetings_production
  username: meetings_dev
  password: <%= ENV['MEETINGS_DATABASE_PASSWORD'] %>
#